### ISSUE TITLE
Refactor runtime config generation

### ISSUE THREAD

**Issue by awisniew90** [dev-tools-for-enterprise-java/boost#324]
With the runtime adapter design, there are two ways that we can manage booster configuration . 

1. Currently, runtimes are able to extend existing booster config classes (i.e. `LibertyJDBCBoosterConfig extends JDBCBoosterConfig`). The extended class can then add whatever configuration that specific runtime needs for that specific booster (i.e. add a datasource)

**Pros**: Considerable flexibility. Configuration is contained at the booster level.
**Cons**: There is more work for the runtime to do to orchestrate configuration. There is no consistent behavior across all runtimes. 

2. As an alternative (or in addition to this extendable booster functionality), we can bring back the `ServerConfigGenerator` interface which would define common configuration tasks like `addHttpEndpoint()`, `addDatasource()`, etc. Runtime would then implement this interface according to how their runtime configures these items. All base booster config classes can have an `addServerConfig()` method. That method would take a ServerConfigGenerator as a parameter and call whatever methods needed for that booster (i.e. the JDBCBoosterConfig class would call `ServerConfigGenerator.addDatasource()'. 

**Pros**: Boosters orchestrate configuration and keep consistent behavior across all runtimes. Simpler config structure for runtimes to implement. 
**Cons**: Potentially large classes implementing ServerConfigGenerator interface. Potentially less flexibility for runtimes. 

As a side note, I think we could have an HttpBoosterConfig class that is always created internally. We could then have this booster manage the reading of boost.http.port properties and call `ServerConfigGenerator.addHttpEndpoint()` and `ServerConfigGenerator.addHostname()`. This would alleviate the runtimes from having to read boost properties and orchestrate the endpoint configuration.

**Comment by scottkurz** [comment]
Assuming this is superseded by @mattbsox's work, so closing for now.
